### ISSUE TITLE
Java compiler

### ISSUE THREAD

**Issue by morpheouss** [juur/fail-jvm#1]
Hey, this JVM implementation is great! Have you thought about writing also a java compiler that could produce a valid .class files for it in place of javac? That would be also a nice tool. I was looking for some alternatives for javac, or even other languages compiler that produces java bytecode, but I found nothing interesting, except some stuff written in Java and thus still requiring JVM and java compiler.

**Comment by juur** [comment]
I have tried a few times to write a compiler, it's quite difficult. There's a lot of the specification of the JVM you can 'ignore' to make a working JVM, but I don't think it's quite the same for the Java language.
Beyond my skill I think.

**Comment by morpheouss** [comment]
If some things are not used on JVM side, they should also be unused in Java, I think. I cannot imagine, you can generate bytecode that cannot be executed. What is more java compiler isnt a typical compiler i think as it generates a bytecode only.
